---
author: Dustin Dortch
name: HCP Vault Get Secret
description: Retrievs a secret from HCP Vault Secrets platform

inputs:
  app:
    default: ''
    description: 'HCP App (optional, if bound to auth token)'
    required: false
  mask:
    default: 'true'
    description: 'Mask secret value in logs'
    required: false
  name:
    description: 'Secret name'
    required: true
  organization_id:
    default: ''
    description: 'HCP Organization ID (optional, if bound to auth token)'
    required: false
  project:
    default: ''
    description: 'HCP Project (optional, if bound to auth token)'
    required: false

outputs:
  secret:
    description: 'Secret value'
    value: ${{ steps.get-secret.outputs.secret }}

runs:
  using: composite
  steps:
    - id: get-secret
      name: Get Secret
      shell: bash
      run: >
        secret=$(hcp vault-secrets secrets open "${{ inputs.name }}"
        ${{ inputs.app != '' && format('--app={0}', inputs.app) || '' }}
        ${{ inputs.organization_id != '' && format('--organization-id={0}', inputs.organization_id) || '' }}
        ${{ inputs.project != '' && format('--project={0}', inputs.project) || '' }}
        --format=json | jq -r '.static_version.value');
        ${{ inputs.mask != 'false' && 'echo "::add-mask::$secret";' || '' }}
        echo "secret=$secret" >> $GITHUB_OUTPUT
...